### ISSUE TITLE
代码训练问题！

### ISSUE THREAD

**Issue by violet2422** [iscyy/ultralyticsPro#71]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

**请问改这些模块，博主用数据集自己训练过吗？最好可以放上一些有说服力的图、表！！！**

**Comment by iscyy** [comment]
1. Because there are too many modules, training COCO requires a lot of GPU resources. Most of the modules have been trained, and some modules can work. The training experimental data will not be released for the time being, which is not necessary.
2. Different data sets perform differently, you can do experiments yourself.
